version: '3.1'

services:
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: document-management
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  app:
    image: thaihoang1409/document-management-app:latest
    environment:
      PORT: 3001
      JWT_SECRET: thaihoangtest
      DATABASE_HOST: db
      DATABASE_PORT: 3306
      DATABASE_USER: root
      DATABASE_PASS: 12345678
      DATABASE_NAME: document-management
    ports:
      - "3001:3001"
    depends_on:
      - db
    command: sh -c "npm run build && ./wait-for-it.sh db:3306 -- npm run start:prod"

  fe:
    image: thaihoang1409/document-management-fe:latest
    environment:
      NEXT_PUBLIC_API: http://localhost:3001/api
      NEXT_PUBLIC_STATIC: http://localhost:3001/
    ports:
      - "3000:3000"
    depends_on:
      - db
    command: sh -c "npm run build && ./wait-for-it.sh db:3306 -- npm run start"

volumes:
  db_data:
