version: '3.1'

services:
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: document-management
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  fe:
    build: .
    environment:
      NEXT_PUBLIC_API: http://localhost:3001/api
      NEXT_PUBLIC_STATIC: http://localhost:3001/
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  db_data:
