export const incomeAttribute = {
    "id": "ID",
    "originalNumber": "Số hiệu gốc văn bản đến",
    "number": "Số văn bản đến",
    "arrivalDate": "Ngày đến",
    "signDate": "Ngày ký",
    "signer": "Người ký",
    "sendFrom": "Nơi gửi",
    "sendTo": "Nơi nhận",
    "emergencyLevel": "Độ khẩn",
    "thematic": "Chuyên đề",
    "leader": "Lãnh đạo giao việc",
    "mainProcessor": "Chủ trì xử lý",
    "category": "Thể loại",
    "abstract": "Trích yếu",
    "status": "Trạng thái",
    "incomeUrl": "File văn bản đến",
    "draftUrl": "File dự thảo",
}